server:
  port: 9000
spring:
  application:
    name: sca-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true #开启服务发现机制，可以从注册中心获取服务
      routes:  #配置路由规则，简单点理解就是请求转发
        - id: route01
          uri: lb://sca-consumer  #lb:loadBalance 表示负载均衡，不能随意写,这里的sca-consumer为服务名
          predicates: ###匹配规则(谓词对象/断言对象)
            - Path=/nacos/consumer/**
          filters: #http://ip:9000/nacos/consumer/**
            - StripPrefix=1 #转发之前去掉path中第一层路径，例如nacos
logging:
  level:
    org.springframework.cloud.gateway: debug